config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'rooms#index'
  resources :users, only: %i[edit update show] do
    member do
      get  'following'
      get  'followers'
      get  'gift_history'
      post 'testgifting', to: 'gifts#test_gifting'
    end
    resources :gifts,     only: %i[index new create]
    resources :profiles,  only: %i[      new create edit update]
    resources :bookmarks, only: %i[index new create             destroy]
  end
  resources :rooms, only: %i[new create destroy] do
    collection do
      get 'search'
    end

    post   'add'  => 'likes#create'
    delete '/add' => 'likes#destroy'
  end
  resources :messages,      only: %i[index create]
  resources :relationships, only: %i[create destroy]
  resources :testsessions,  only: :create
  resources :notifications, only: :index
  resources :game_tags,     only: %i[] do
    member do
      get 'tag_search'
    end
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  mount_uploader :image, ImageUploader
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :check_if_user_signed_in

  def new
    @user = User.find(params[:user_id])
    user =  User.find(params[:user_id])
    redirect_to root_path unless current_user == user
  end

  def create
    @profile = Profile.new(profile_params)
    if @profile.save
      redirect_to user_path(current_user)
    else
      render :new
    end
  end

  def edit
    @profile = Profile.find_by(user: current_user)
    @user =    User.find(params[:id])
    redirect_to root_path unless current_user == @user
  end

  def update
    @profile = Profile.find_by(user: current_user)
    if @profile.update(edit_profile_params)
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  private

  def profile_params
    params.permit(:link_to_sns, :link_to_webcast, :self_introduction, :image).merge(user_id: current_user.id)
  end

  def edit_profile_params
    params.require(:profile).permit(:link_to_sns, :link_to_webcast, :self_introduction, :image).merge(user_id: current_user.id)
  end

  def check_if_user_signed_in
    redirect_to new_user_session_path unless user_signed_in?
  end
end

app/views/profiles/edit.html.erb
<%= render partial: "rooms/navigation_menu" %>
<div class="main__user-profile">
  <%= render partial: "users/user-profile__left", locals: { user: @user } %>

  <div class="main-contents">
    <div class="content">
      <div class="index">
        <div class="index-tag">
          <span class="action-title"><%= "プロフィールを変更" %></span>
        </div>
        <div class="index-decoration"></div>
      </div>
      <div class="room-name">
        <div class="question-space">
          <%= form_with(url: user_profile_path(current_user), model: @profile, local: true, method: :patch) do |f| %>
            <div class="user-profile-edit-form">
              <div class="click-upload">
                <div id="image-list">
                  <% profile = @profile %>
                  <% if profile %>
                    <% if profile.image? %>
                      <%= image_tag(profile.image.url, size: "100x100", id:"before_image")%> 
                    <% else %> 
                      <%= image_tag "/assets/default.jpg", :size => '100x100', id:"before_image" %> 
                    <% end %>
                  <% end %>
                </div>
                <label for="profile-image", class="image-label">画像を選択
                  <%= f.file_field :image, id:"profile-image", class:"image-file" %>
                </label>
              </div>

              <div class="user-nickname__space">
                <span class="user-nickname__display"><%= current_user.nickname %></span>
                <div class="user-nickname-edit__hover-action">
                  <% unless current_user.email == "test_user@test.com" %>
                    <%= link_to "編集する", edit_user_path(current_user), class:"user-nickname-edit__hover" %>
                  <% end %>
                </div>
              </div>

              <div class="link-to-sns__space">
                <label for="user-profile-SNS", class="link-to-sns">SNS</label>
                <div>
                  <%= f.text_field :link_to_sns, class: 'form-message', placeholder: 'https://', id:"user-profile-SNS"%>
                </div>
              </div>

              <div class="link-to-webcast__space">
                <label for="user-profile-webcast", class="link-to-webcast">配信サイト</label>
                <div>
                  <%= f.text_field :link_to_webcast, class: 'form-message', placeholder: 'https://', id:"user-profile-webcast"%>
                </div>
              </div>

              <div class="link-to-introduction__space">
                <label for="user-profile-self-introduction", class="self-introduction">自己紹介</label>
                <div>
                  <%= f.text_area :self_introduction, class: 'form-text-area', id:"user-profile-self-introduction"%>
                </div>
              </div>

              <div class="user-edit__hover-action hover-action">
                <span class='user-edit__normal btn__normal'>更新</span>
                <span><%= f.submit '更新', class: 'user-edit__hover btn__hover' %></span>
              </div>

              <div class="user-nickname-edit__hover-action">
                <% unless current_user.email == "test_user@test.com" %>
                  <%= link_to "メールアドレスを変更", edit_user_path(current_user), class:"user-nickname-edit__hover" %>
                <% end %>
              </div>
            
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/profiles/new.html.erb
<%= render partial: "rooms/navigation_menu" %>
<div class="main__user-profile">
  <%= render partial: "users/user-profile__left", locals: { user: @user } %>

  <div class="main-contents">
    <div class="content">
      <div class="index">
        <div class="index-tag">
          <span class="action-title"><%= "プロフィールを変更" %></span>
        </div>
        <div class="index-decoration"></div>
      </div>
      <div class="room-name">
        <div class="question-space">
          <%= form_with(url: user_profiles_path(current_user), model: @profile, local: true, method: :post) do |f| %>
            <div class="user-profile-edit-form">
              <div class="click-upload">
                <div id="image-list">
                  <% profile = current_user.profile %>
                  <% if profile %>
                    <% if profile.image? %>
                        <%= image_tag(profile.image.url, size: "100x100", id:"before_image")%> 
                    <% end %>
                  <% else %>
                    <%= image_tag "/assets/default.jpg", :size => '100x100', id:"before_image" %> 
                  <% end %>

                </div>
                <label for="profile-image", class="image-label">画像を選択
                  <%= f.file_field :image, accept: 'image/jpeg,image/gif,image/png', id:"profile-image", class:"image-file" %>
                </label>
              </div>

              <div class="user-nickname__space">
                <span class="user-nickname__display"><%= current_user.nickname %></span>
                <div class="user-nickname-edit__hover-action">
                  <%= link_to "編集する", edit_user_path(current_user), class:"user-nickname-edit__hover" %>
                </div>
              </div>
            
              <div class="link-to-sns__space">
                <label for="user-profile-SNS", class="link-to-sns">SNS</label>
                <div>
                  <%= f.text_field :link_to_sns, class: 'form-message', placeholder: 'https://', id:"user-profile-SNS"%>
                </div>
              </div>

              <div class="link-to-webcast__space">
                <label for="user-profile-webcast", class="link-to-webcast">配信サイト</label>
                <div>
                  <%= f.text_field :link_to_webcast, class: 'form-message', placeholder: 'https://', id:"user-profile-webcast"%>
                </div>
              </div>

              <div class="link-to-introduction__space">
                <label for="user-profile-self-introduction", class="self-introduction">自己紹介</label>
                <div>
                  <%= f.text_area :self_introduction, class: 'form-text-area', id:"user-profile-self-introduction"%>
                </div>
              </div>

              <div class="user-edit__hover-action">
                <span class='user-edit__normal'>登録</span>
                <span><%= f.submit '登録', class: 'user-edit__hover' %></span>
              </div>

              <div class="user-nickname-edit__hover-action">
                <%= link_to "メールアドレスを変更", edit_user_path(current_user), class:"user-nickname-edit__hover" %>
              </div>
            
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>