config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'rooms#index'
  resources :users, only: %i[edit update show] do
    member do
      get  'following'
      get  'followers'
      get  'gift_history'
      post 'testgifting', to: 'gifts#test_gifting'
    end
    resources :gifts,     only: %i[index new create]
    resources :profiles,  only: %i[      new create edit update]
    resources :bookmarks, only: %i[index new create             destroy]
  end
  resources :rooms, only: %i[new create destroy] do
    collection do
      get 'search'
    end

    post   'add'  => 'likes#create'
    delete '/add' => 'likes#destroy'
  end
  resources :messages,      only: %i[index create]
  resources :relationships, only: %i[create destroy]
  resources :testsessions,  only: :create
  resources :notifications, only: :index
  resources :game_tags,     only: %i[] do
    member do
      get 'tag_search'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true

  # 質問に関するアソシエーション
  has_many :entries
  has_many :rooms, through: :entries
  has_many :messages
  # ギフトに関するアソシエーション
  has_many :gifts
  has_many :receivers, through: :gifts, source: :giver
  has_many :reverse_of_gifts, class_name: 'Gift', foreign_key: 'giver_id'
  has_many :giftings, through: :reverse_of_gifts, source: :user
  # ゲームお気に入り登録に関するアソシエーション
  has_many :bookmarks
  has_many :game_tags, through: :bookmarks
  # フォローに関するアソシエーション
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user
  # プロフィールに関するアソシエーション
  has_one  :profile
  # いいねに関するアソシエーション
  has_many :likes, dependent: :destroy
  has_many :like_rooms, through: :likes, source: :room
  # 通知に関するアソシエーション
  has_many :active_notifications,  class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  def follow(other_user) # フォローする！！
    relationships.find_or_create_by(follow_id: other_user.id) unless self == other_user # フォローしようとしているユーザーが自分自身か！
  end

  def following?(other_user) # そのユーザーは既にフォローしてる？かを確認する！
    followings.include?(other_user)
  end

  def create_notification_follow!(current_user)
    temp = Notification.where(['visitor_id = ? and visited_id = ? and action = ? ', current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end

  def create_notification_gift!(current_user)
    temp = Notification.where(['visitor_id = ? and visited_id = ? and action = ? ', current_user.id, id, 'gift'])
    notification = current_user.active_notifications.new(
      visited_id: id,
      action: 'gift'
    )
    notification.save if notification.valid?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_if_user_signed_in
  def edit; end

  def update
    if current_user.update(user_params)
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  def show
    @user = User.find(params[:id])
    rooms =            Room.preload(:likes, :game_tags, messages: :user).all.order('created_at DESC')
    questions =        Room.user_questions(@user, rooms)
    other_questions =  Room.user_other_questions
    @questions =       Kaminari.paginate_array(questions).page(params[:page]).per(5)
    @other_questions = Kaminari.paginate_array(other_questions).page(params[:page]).per(5)
  end

  def following
    @user = User.find(params[:id])
    @all_following = @user.followings
    @all_following = Kaminari.paginate_array(@all_following).page(params[:page]).per(10)
  end

  def followers
    @user = User.find(params[:id])
    @all_followers = @user.followers
    @all_followers = Kaminari.paginate_array(@all_followers).page(params[:page]).per(10)
  end

  def gift_history
    @user = User.find(params[:id])
    redirect_to root_path unless current_user == @user
    if user_signed_in?
      @giftings   = Gift.where(giver_id: current_user.id).page(params[:page]).per(8).order('created_at DESC')
      @receivings = Gift.where(user_id:  current_user.id).page(params[:page]).per(8).order('created_at DESC')
    end
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :email)
  end

  def check_if_user_signed_in
    redirect_to new_user_session_path unless user_signed_in?
  end
end

app/views/users/_giftings.html.erb
<div class="main-content">
  <% profile = user.profile %>
  <div class="icons-space">
    <%= link_to user_path(user) do %>
      <% if profile %>
        <% if profile.image? %>
          <%= image_tag(profile.image.thumb50.url, class: "question-user-icon")%>
        <% end %>
      <% else %>
        <%= image_tag "question_user_icon.png", class:"question-user-icon" %>
      <% end %>
    <% end %>
  </div>
        
  <div class="question-texts">
    <div class="question-nickname">
      <%= "#{user.nickname}さん" %>
    </div>

    <div class="question-sentence">
      <div class="question-content">
        <%= "#{gift.price}円"%>
      </div>
    </div>
  </div>
</div>

app/views/users/_related_to_follow.html.erb
<div class="main-content">
  <% profile = user.profile %>
  <div class="icons-space">
    <%= link_to user_path(user) do %>
      <% if profile %>
        <% if profile.image? %>
          <%= image_tag(profile.image.thumb50.url, class: "question-user-icon")%>
        <% end %>
      <% else %>
        <%= image_tag "question_user_icon.png", class:"question-user-icon" %>
      <% end %>
    <% end %>
  </div>
        
  <div class="question-texts">
    <div class="question-nickname">
      <%= "#{user.nickname}さん" %>
    </div>

    <div class="question-sentence">
      <div class="question-content">
        <% if profile %>
          <% if profile.self_introduction? %>
            <span class="self_introduction"><%= safe_join(profile.self_introduction.split("\n"),tag(:br))%></span>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/_user-profile__left.html.erb
<div class="user-profile">
  <% profile = user.profile %>
  <% if profile %>
    <% if profile.image? %>
      <%= image_tag(profile.image.thumb100.url, class: "user-profile-icon") %>
    <% else %>
      <%= image_tag "default.jpg", class: "user-profile-icon" %>
    <% end %>

    <div class="user-nickmane__space">
      <span class="user-nickname"><%= user.nickname %></span>
    </div>

    <div class="link-icons">
      <% if profile.link_to_sns? %>
        <%= link_to profile.link_to_sns, target: "_blank" do %>
          <%= image_tag "twitter_icon.png", class:"twitter-icon" %>
        <% end %>
      <% end %>
    </div>

    <div class="link-icons">
      <% if profile.link_to_webcast? %>
        <%= link_to profile.link_to_webcast, target: "_blank" do %>
          <%= image_tag "webcast_icon.png", class:"webcast-icon" %>
        <% end %>
      <% end %>
    </div>

    <div class="self_introduction__space">
      <% if user.profile.self_introduction? %>
        <span class="self_introduction"><%= safe_join(user.profile.self_introduction.split("\n"),tag(:br))%></span>
      <% end %>
    </div>
  <% end %>

  <% if user == current_user %>
       <div class="profile__hover-action hover-action">
    <% if user.profile == nil %>
        <span class='profile-btn__normal btn__normal'>プロフィールを登録</span>
        <span><%= link_to "プロフィールを登録", new_user_profile_path(current_user), class: 'profile-btn__hover btn__hover' %></span>
    <% else %>
      <% unless current_page?("/users/#{current_user.id}/bookmarks") || current_page?("/users/#{current_user.id}/bookmarks/new") || current_page?("/notifications") %>
        <span class='profile-btn__normal btn__normal'>プロフィールを編集</span>
        <span><%= link_to "プロフィールを編集", edit_user_profile_path(current_user), class: 'profile-btn__hover btn__hover' %></span>
      <% else %>
        <span class='profile-btn__normal btn__normal'>マイページに戻る</span>
        <span><%= link_to "マイページに戻る", user_path(current_user), class: 'profile-btn__hover btn__hover' %></span>
      <% end %>
    <% end %>
    </div>

    <div class="gift__hover-action hover-action">
      <span class='gift-btn__normal btn__normal'><i class="fas fa-gift" style="color: rgb(255, 62, 62);"></i> ギフト情報</span>
      <span>
        <%= link_to gift_history_user_path(user), class: 'gift-btn__hover btn__hover' do %>
          <i class="fas fa-gift" style="color: rgb(255, 62, 62);"></i><%= ' ギフト情報' %>
        <% end %>
      </span>
    </div>

  <% elsif user_signed_in? %>
    <%= render 'relationships/follow_button', user: user %>

    <div class="gift__hover-action hover-action">
      <span class='gift-btn__normal btn__normal'><i class="fas fa-gift" style="color: rgb(255, 62, 62);"></i> ギフトする</span>
      <span>
        <%= link_to user_gifts_path(user), class: 'gift-btn__hover btn__hover' do %>
          <i class="fas fa-gift" style="color: rgb(255, 62, 62);"></i><%= ' ギフトする' %>
        <% end %>
      </span>
    </div>
    
  <% else %>
    <div class="follow__hover-action">
      <span class='follow-btn__normal'>フォロー</span>
      <span><%= link_to 'フォロー', new_user_session_path, class: 'follow-btn__hover' %></span>
    </div>

    <div class="gift__hover-action">
      <span class='gift-btn__normal'>ギフト</span>
      <span><%= link_to 'ギフト', new_user_session_path, class: 'gift-btn__hover' %></span>
    </div>
  <% end %>

  <div class="follow__space">
    <div class="followings__space">
      <div class="followings-size">
        <%= user.followings.size %>
      </div>
      <div class="followings__hover-action">
        <%= link_to 'フォロー', following_user_path(user), class:"followings" %>
      </div>
    </div>

    <div class="followers__space">
      <div class="followers-size">
        <%= user.followers.size %>
      </div>
      <div class="followers__hover-action">
        <%= link_to 'フォロワー', followers_user_path(user), class:"followers" %>
      </div>
    </div>
  </div>
</div>

app/views/users/bookmark.html.erb
<%= render partial: "rooms/navigation_menu" %>

<div class="main__user-profile">

  <%= render partial: "user-profile__left", locals: { user: @user } %>

  <div class="user-question-contents">

    <div class="content">
      <div class="index">
        <div class="index__game_tag">
          <span class="index-name__bookmark"><%= "好きなゲーム" %></span>
        </div>
        <div class="index__triangle"></div>
      </div>
      <div class="room-name">
        <div class="game_tag__space">
          <% Bookmark.where(user_id: @user.id).each do |game| %>
            <div class="game_tag">
              <%= game.game_tag.game_title %>
            </div>
          <% end %>
          <div class="game_tag__registration__hover-action">
          </div>
        </div>
      </div>
    </div>

    <div class="content">
      <div class="index">
        <div class="index__game_tag">
          <span class="bookmark-action-title"><%= "ゲームを登録する" %></span>
        </div>
        <div class="index__triangle"></div>
      </div>
      <div class="room-name">
        <%= form_with(url: bookmark_user_path(current_user), model: @bookmark, local: true, method: :get) do |f| %>
          <div class="game-tag__form-space">
            <div class="game-tag__choose-space">
              <select name="game_tag_id" , class="game-tag__choose"> 
                <option value=""hidden disabled selected>---</option>
                <% GameTag.all.where.not(id: @bookmarked_game_tags).each do |tag| %> <%#同じゲームはお気に入り登録できない！%>
                    <option value=<%=tag.id%>><%= tag.game_title %></option>
                <% end %>
              </select>
            </div>
            <div class="game-tag__hover-action">
              <label for="bookmark-btn", class='game-tag__submit-btn__normal'>登録</label>
              <%= f.submit value="登録", class: 'game-tag__submit-btn__hover', id:"bookmark-btn" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<%= render partial: "rooms/navigation_menu" %>
<div class="main__user-profile">
  <%= render partial: "users/user-profile__left", locals: { user: current_user } %>

  <div class="main-contents">
    <div class="content">
      <div class="index">
        <div class="index-tag">
          <span class="action-title"><%= "プロフィールを変更" %></span>
        </div>
        <div class="index-decoration"></div>
      </div>
      <div class="room-name">
        <div class="question-space">
          <%= form_with model: current_user, local: true do |f|%>
            <div class="user-profile-edit-form">
              <div class="click-upload">
                <div id="image-list">
                  <% profile = current_user.profile %>
                  <% if profile %>
                    <% if profile.image? %>
                      <%= image_tag(profile.image.url, size: "100x100", id:"before_image")%> 
                    <% else %> 
                      <%= image_tag "/assets/default.jpg", :size => '100x100', id:"before_image" %> 
                    <% end %>
                  <% end %>
                </div>
              </div>

              <div class="user-nickname__space">
                <span class="user-nickname__display"><%= current_user.nickname %></span>

              </div>

              <div class="link-to-sns__space">
                <div class="link-to-sns"><%= "ニックネーム" %></div>
                <div><%= f.text_field :nickname, autofocus: true, class: 'form-message'%></div>
              </div>
            
              <div class="link-to-sns__space">
                <div class="link-to-sns"><%= "メールアドレス" %></div>
                <div><%= f.email_field :email, class: 'form-message'%></div>
              </div>

              <div class="user-edit__hover-action">
                <span class='user-edit__normal'>更新</span>
                <span><%= f.submit '更新', class: 'user-edit__hover' %></span>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/followers.html.erb
<%= render partial: "rooms/navigation_menu" %>
<div class="main__user-profile">
  <%= render partial: "user-profile__left", locals: { user: @user } %>

  <div class="main-contents">
    <div class="content">
      <div class="index">
        <div class="index-tag">
          <span class="action-title"><%= "フォロー" %></span>
        </div>
        <div class="index-decoration"></div>
      </div>
      <div class="room-name">
        <div class="question-space">
          <% @all_followers.each do |follower| %>
            <%= render partial: "related_to_follow", locals: { user: follower } %>
          <% end %>
          <%= paginate @all_followers %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/following.html.erb
<%= render partial: "rooms/navigation_menu" %>
<div class="main__user-profile">

  <%= render partial: "user-profile__left", locals: { user: @user } %>

  <div class="main-contents">
    <div class="content">
      <div class="index">
        <div class="index-tag">
          <span class="action-title"><%= "フォロワー" %></span>
        </div>
        <div class="index-decoration"></div>
      </div>
      <div class="room-name">
        <div class="question-space">
          <% @all_following.each do |following| %>
            <%= render partial: "related_to_follow", locals: { user: following } %>
          <% end %>
          <%= paginate @all_following %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/gift_history.html.erb
<%= render partial: "rooms/navigation_menu" %>
<div class="main__user-profile">

  <%= render partial: "user-profile__left", locals: { user: @user } %>

  <div class="main-contents">
<%# ここから、自分がしたギフト！ %>
    <div class="content">
      <div class="index">
        <div class="index-tag">
          <span class="action-title"><%= "自分がしたギフト" %></span>
        </div>
        <div class="index-decoration"></div>
      </div>
      <div class="room-name">
        <div class="question-space">
          <% @giftings.each do |gift| %>
            <%= render partial: "giftings", locals: { gift: gift, user: gift.user } %>
          <% end%>
          <%= paginate @giftings %>
        </div>
      </div>
    </div>
<%# ここまで、自分がしたギフト！ %>

<%# ここから、自分に送られたギフト！ %>
    <div class="content">
      <div class="index">
        <div class="index-tag">
          <span class="action-title"><%= "自分に送られたギフト" %></span>
        </div>
        <div class="index-decoration"></div>
      </div>
      <div class="room-name">
        <div class="question-space">
          <% @receivings.each do |gift| %>
            <%= render partial: "giftings", locals: { gift: gift, user: gift.giver } %>
          <% end%>
          <%= paginate @receivings %>
        </div>
      </div>
    </div>
<%# ここまで、自分に送られたギフト！ %>

  </div>
</div>

app/views/users/gifts.html.erb
<%= render partial: "rooms/navigation_menu" %>
<div class="main__user-profile">
  <div class="user-profile">
  <% unless @user.profile == nil %>

      <% if @user.profile.image? %>
        <p><%= image_tag(@user.profile.image.thumb100.url, class: "user-profile-icon") %></p>
      <% else %>
        <%= image_tag "default.jpg", :size => '50x50' %>
      <% end %>
      <% if @user.profile.link_to_sns? %>
        <%= link_to @user.profile.link_to_sns, target: "_blank" do %>
          <%= image_tag "twitter_icon.png", class:"twitter-icon" %>
        <% end %>
      <% end %>
      <% if @user.profile.link_to_webcast? %>
        <%= link_to @user.profile.link_to_webcast, target: "_blank" do %>
          <%= image_tag "webcast_icon.png", class:"webcast-icon" %>
        <% end %>
      <% end %>
      <% if @user.profile.self_introduction? %>
        <p><%= safe_join(@user.profile.self_introduction.split("\n"),tag(:br))%></p>
      <% else %>
        <p><%= "自己紹介分は設定されていません" %></p>
      <% end %>
    <% end %>

    <% if @user == current_user %>
      <% if @user.profile == nil %>
        <p><%= link_to "プロフィールを新しく設定する", new_user_profile_path(current_user) %></p>
      <% else %>
        <p><%= link_to "プロフィールを編集する", edit_user_profile_path(current_user) %></p>
      <% end %>

    <p><%= link_to 'ギフト情報', gifts_user_path(@user) %></p>
    <% elsif user_signed_in? %>
      <%= link_to 'ギフトする！', user_gifts_path(@user) %>
      <%= render 'relationships/follow_button', user: @user %>
    <% else %>
      <%= link_to 'ギフトする！', new_user_session_path %>
    <% end %>

    <p><%= @user.followings.size %><%= link_to 'フォロー', following_user_path(@user) %></p>
    <p><%= @user.followers.size %><%= link_to 'フォロワー', followers_user_path(@user) %></p>
  </div>

  <div class="user-question-contents">
    <div class="gift-action">
        <p class="gift-action-title">自分がしたギフト</p>
        <% @giftings.each do |gift| %>
          <div class="gifts">
            <p class="gift"><%= "#{gift.user.nickname}に#{gift.price}円をギフトした！" %></p>
          </div>
        <% end %>
      </div>
      <div class="gift-action">
        <p class="gift-action-title">自分に送られたギフト</p>
        <% @receivings.each do |gift| %> 
          <div class="gifts">
            <p class="gift"><%= "#{gift.giver.nickname}から#{gift.price}円をギフトされた！感謝します！" %></p>
          </div>
        <% end %> 
      </div> 

  </div>
</div>

app/views/users/show.html.erb
<%= render partial: "rooms/navigation_menu" %>

<div class="main__user-profile">

  <%= render partial: "user-profile__left", locals: { user: @user } %>

  <div class="main-contents">
  
     <div class="content">
      <div class="index">
        <div class="index-tag">
          <span class="index-name"><%= "好きなゲーム" %></span>
        </div>
        <div class="index-decoration"></div>
      </div>
      <div class="room-name">
        <div class="game_tag__space">
          <% Bookmark.preload(:game_tag).where(user_id: @user.id).each do |game| %>
            <div class="game_tag">
              <%= link_to tag_search_game_tag_path(game.game_tag.id), class: 'game_tag__registration' do %>
                <%= game.game_tag.game_title %>
              <% end %>
            </div>
          <% end %>

          <% if user_signed_in? && current_user == @user %>
            <div class="game_tag__hover-action">
              <%= link_to "ゲームを登録する", user_bookmarks_path(current_user), class: 'game_tag__registration' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <%= "#{@user.nickname}さんが回答した質問" %>
    <% @questions.each do |question| %>
          <%= render partial: "rooms/questions", locals: { question: question } %>
    <% end %>
    <%= paginate @questions %>

    <% if  current_user == @user %>
      <%= "自分の質問" %>
    <% else %>
      <%= "#{@user.nickname}さんの質問" %>
    <% end%>
    <% @other_questions.each do |question| %>
          <%= render partial: "rooms/questions", locals: { question: question } %>
    <% end %>
    <%= paginate @other_questions %>
  </div>
</div>