config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'rooms#index'
  resources :users, only: %i[edit update show] do
    member do
      get  'following'
      get  'followers'
      get  'gift_history'
      post 'testgifting', to: 'gifts#test_gifting'
    end
    resources :gifts,     only: %i[index new create]
    resources :profiles,  only: %i[      new create edit update]
    resources :bookmarks, only: %i[index new create             destroy]
  end
  resources :rooms, only: %i[new create destroy] do
    collection do
      get 'search'
    end

    post   'add'  => 'likes#create'
    delete '/add' => 'likes#destroy'
  end
  resources :messages,      only: %i[index create]
  resources :relationships, only: %i[create destroy]
  resources :testsessions,  only: :create
  resources :notifications, only: :index
  resources :game_tags,     only: %i[] do
    member do
      get 'tag_search'
    end
  end
end

app/models/gift.rb
class Gift < ApplicationRecord
  belongs_to :user
  belongs_to :giver, class_name: 'User'

  attr_accessor :token

  validates :user_id, presence: true
  validates :giver_id, presence: true
  validates :price, presence: true
  validates :token, presence: true

  validates :price, numericality: { greater_than_or_equal_to: 300,
                                    message: 'が範囲外です',
                                    less_than_or_equal_to: 50_000
                                  }

  validates :price, numericality: { only_integer: true,
                                    message: 'は半角数字で入力してください' 
                                  }
end

app/controllers/gifts_controller.rb
class GiftsController < ApplicationController
  before_action :check_if_user_signed_in

  def index
    @user =    User.find(params[:user_id])
    @reciver = User.find(params[:user_id])
    redirect_to root_path if @reciver == current_user
    @gift = Gift.new
  end

  def new; end

  def create
    @reciver = User.find(params[:user_id])
    @user =    User.find(params[:user_id])
    @gift =    Gift.new(order_params)
    if @gift.valid?
      pay_item
      @gift.save
      @reciver.create_notification_gift!(current_user)
      redirect_to root_path
    else
      render 'index'
    end
  end

  def test_gifting
    reciver = User.find(params[:id])
    gift = Gift.create(
      price:    500,
      user_id:  reciver.id,
      giver_id: current_user.id,
      token:    'test'
    )
    redirect_to root_path
  end

  private

  def order_params
    params.require(:gift).permit(:price).merge(user_id: @reciver.id, giver_id: current_user.id, token: params[:token])
  end

  def pay_item
    Payjp.api_key = ENV['PAYJP_SECRET_KEY']  # PAY.JPテスト秘密鍵
    Payjp::Charge.create(
      amount:   order_params[:price], # 商品の値段
      card:     params[:token], # カードトークン
      currency: 'jpy'                 # 通貨の種類(日本円)
    )
  end

  def check_if_user_signed_in
    redirect_to new_user_session_path unless user_signed_in?
  end
end

app/views/gifts/index.html.erb
<%= render partial: "rooms/navigation_menu" %>
<div class="main__user-profile">
  <%= render partial: "users/user-profile__left", locals: { user: @user } %>
  <div class="main-contents">
    <div class="content">
      <div class="index">
        <div class="index-tag">
          <span class="action-name"><%= "ギフトする" %></span>
        </div>
        <div class="index-decoration"></div>
      </div>
      <div class="room-name">
        <div class="gift-form__space">

        <div class="gift-users">
          <div class="gift-image__space">
          <% profile_giver = current_user.profile %>
          <% if profile_giver %>
            <% if profile_giver.image? %>
              <%= image_tag(profile_giver.image.thumb100.url, class: "user-profile-icon") %>
            <% else %>
              <%= image_tag "default.jpg", class: "user-profile-icon" %>
            <% end %>
          <% end %>

            <div class="user-nickmane__space">
              <span class="user-nickname"><%= "#{current_user.nickname}さん" %></span>
            </div>
          </div>

          <div class="image__space-present animate__animated animate__backInLeft">
            <div><%= image_tag "present-icon.png", class: "image__space-present-icon" %></div>
          </div>

          <div class="gift-image__space">
            <% profile_reciver = @reciver.profile %>
            <% if profile_reciver %>
              <% if profile_reciver.image? %>
                <%= image_tag(profile_reciver.image.thumb100.url, class: "user-profile-icon") %>
              <% else %>
                <%= image_tag "default.jpg", class: "user-profile-icon" %>
              <% end %>
            <% end %>
            <div class="user-nickmane__space">
              <span class="user-nickname"><%= "#{@reciver.nickname}さん" %></span>
            </div>
          </div>
        </div>

          <%= form_with model: [@reciver, @gift], url: user_gifts_path, method: :post, id: 'charge-form', class: 'transaction-form-wrap',local: true do |f|  %>
            <%= render 'shared/error_messages', model: f.object %>
            <div class="gift-form">
              <div class='price__space'>
                <label class="gift-form-text">ギフトする金額</label>
                <span class="gift-price-range">(300~50000円)</span>
              </div>
              <span><%= f.text_field :price, class:"input-default price-setting", id:"postal-code", maxlength:"5" %></span>円
            </div>
            
            <div class="card-info">
              <span>カード情報</span>
            </div>
            <div class="gift-form">
              <div class='gift-form-text__card-space'>
                <label class="gift-form-text">カード番号</label>
              </div>
              <span>
                <%= f.text_field :number, class:"input-default card-number-setting", id:"card-number", maxlength:"16" %>
                <div class='available-card'>
                  <%= image_tag 'card-visa.gif', class: 'card-logo'%>
                  <%= image_tag 'card-mastercard.gif', class: 'card-logo'%>
                  <%= image_tag 'card-jcb.gif', class: 'card-logo'%>
                  <%= image_tag 'card-amex.gif', class: 'card-logo'%>
                </div>
              </span>
            </div>

            <div class="gift-form">
              <div class='gift-expiration-date'>
                <label class="gift-form-text">有効期限</label>
              </div>
              <div class='gift-expiration-date__space'>
                <%= f.text_field :exp_month, class:"input-expiration", id:"card-exp-month" %>
                <p class="expiration-month__space">月</p>
                <span class="month-20__space">20</span>
                <%= f.text_field :exp_year, class:"input-expiration", id:"card-exp-year" %>
                <p>年</p>
              </div>
            </div>

            <div class="gift-form">
              <div class='gift-cvc'>
                <label class="gift-form-text">セキュリティコード</label>
              </div>
              <span><%= f.text_field :cvc,class:"input-default-cvc", id:"card-cvc", maxlength:"4" %></span>
            </div>

            <div class="gift-submit__hover-action hover-action">
              <label for="gifting-btn", class='gift-btn__normal gift-submit__normal btn__normal'>ギフトを確定</label>
              <%= f.submit "ギフトを確定" ,class:"gift-submit__hover btn__hover", id:"gifting-btn" %>
            </div>

            <div class="test-gift__hover-action hover-action">
              <label for="gifting-btn", class='gift-btn__normal test-gift__normal btn__normal'>簡単ギフト</label>
              <%= link_to '簡単ギフト', testgifting_user_path(@reciver), method: :post, class:"test-submit__hover btn__hover" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>