config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'rooms#index'
  resources :users, only: %i[edit update show] do
    member do
      get  'following'
      get  'followers'
      get  'gift_history'
      post 'testgifting', to: 'gifts#test_gifting'
    end
    resources :gifts,     only: %i[index new create]
    resources :profiles,  only: %i[      new create edit update]
    resources :bookmarks, only: %i[index new create             destroy]
  end
  resources :rooms, only: %i[new create destroy] do
    collection do
      get 'search'
    end

    post   'add'  => 'likes#create'
    delete '/add' => 'likes#destroy'
  end
  resources :messages,      only: %i[index create]
  resources :relationships, only: %i[create destroy]
  resources :testsessions,  only: :create
  resources :notifications, only: :index
  resources :game_tags,     only: %i[] do
    member do
      get 'tag_search'
    end
  end
end

app/models/room.rb
class Room < ApplicationRecord
  # 質問に関するアソシエーション
  has_many :entries
  has_many :users, through: :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
  # ゲームタグに関するアソシエーション
  has_many :room_game_tags
  has_many :game_tags, through: :room_game_tags, dependent: :destroy
  # いいねに関するアソシエーション
  has_many :likes
  has_many :likers, through: :likes, source: :user, dependent: :destroy
  # 通知に関するアソシエーション
  has_many :notifications, dependent: :destroy

  validates :question_title, presence: true

  # 質問一覧表示
  def self.questions(current_user, rooms)
    @rooms = rooms
    @questions = []
    temporary_questions = Entry.where(user_id: current_user.id).order('created_at DESC')
    temporary_questions.preload(room: [:likes, :game_tags, messages: :user]).each do |entry|
      @questions << entry.room
    end
    @questions
  end

  def self.other_questions
    other_questions = []
    temporary_other_questions = @rooms - @questions
    temporary_other_questions.each do |room|
      other_questions << room if room.messages.size == 2
    end
    other_questions
  end

  # 質問検索
  def self.search(current_user, search)
    @search_questions = []
    @rooms = if search != ''
               Room.where('question_title LIKE(?)', "%#{search}%")
             else
               Room.all
             end
    @rooms.each do |room|
      @search_questions << room if room.user_ids.include?(current_user.id)
    end
    @search_questions
  end

  def self.search_other_questions
    other_questions = []
    temporary_other_questions = @rooms - @search_questions
    temporary_other_questions.each do |room|
      other_questions << room if room.messages.size == 2
    end
    other_questions
  end

  # ユーザー詳細ページにおける、質問一覧表示
  def self.user_questions(user, _rooms)
    questions = []
    @user_other_questions = []
    temporary_questions = Entry.preload(room: [:likes, :game_tags, messages: :user]).where(user_id: user.id).order('created_at DESC')
    temporary_questions.each do |entry|
      questions << entry.room if entry.room.messages.size == 2 && entry.room.messages[1].user == user
      @user_other_questions << entry.room if entry.room.messages[0].user == user
    end
    questions
  end

  class << self
    attr_reader :user_other_questions
  end

  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end

  def create_notification_like!(current_user)
    # すでに「いいね」されているか検索
    temp = Notification.where(['visitor_id = ? and visited_id = ? and room_id = ? and action = ? ', current_user.id, users[1].id, id, 'like'])
    # いいねされていない場合のみ、通知レコードを作成
    if temp.blank?
      # 回答者への通知インスタンスを作成
      notification_answer = current_user.active_notifications.new(
        room_id: id,
        visited_id: users[1].id,
        action: 'like'
      )
      # 質問者への通知インスタンスを作成
      notification_questioner = current_user.active_notifications.new(
        room_id: id,
        visited_id: users[0].id,
        action: 'like'
      )
      # 自分自身の投稿に対するいいねの場合は、通知済みとする
      if notification_answer.visitor_id == current_user.id || notification_answer.visited_id == current_user.id
        notification_answer.checked = true
      end
      # 質問者と回答者への通知をレコードにコミットする
      if notification_answer.valid?
        notification_answer.save
        notification_questioner.save
      end
    end
  end

  def create_notification_comment!(current_user, message_id, user_id)
    # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
    temp_ids = Message.select(:user_id).where(room_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, message_id, temp_id['user_id'])
    end
    # まだ誰もコメントしていない場合は、投稿者に通知を送る
    save_notification_comment!(current_user, message_id, user_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_user, message_id, visited_id)
    # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
    notification = current_user.active_notifications.new(
      room_id: id,
      message_id: message_id,
      visited_id: visited_id,
      action: 'message'
    )
    # 自分の投稿に対するコメントの場合は、通知済みとする
    notification.checked = true if notification.visitor_id == notification.visited_id
    notification.save if notification.valid?
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :check_if_user_signed_in, only: %i[new create search destroy]

  def index
    if user_signed_in?
      rooms =            Room.preload(:game_tags, messages: :user).all.order('created_at DESC')
      @users =           User.all
      @questions =       Room.questions(current_user, rooms)
      other_questions =  Room.other_questions
      @other_questions = Kaminari.paginate_array(other_questions).page(params[:page]).per(10)
    end

    # 質問フォーム用の変数
    @room = RoomMessage.new
    @message = Message.new
  end

  def new
    @room = RoomMessage.new
  end

  def create
    @room = RoomMessage.new(room_params)
    if @room.valid?
      @room.save
      n = Room.order(updated_at: :desc).limit(1)
      # 各引数の説明。質問者、質問本文、回答者
      n[0].create_notification_comment!(current_user, n[0].messages[0].id, n[0].entries[0].user_id)
      render json: {
                     room:    @room,
                     tag:     GameTag.find(@room.game_tag_ids[0]),
                     user:    User.find(@room.user_id),
                     content: @room.content
                    }
    else
      render json: {
                     title_err:   @room.errors.messages[:question_title][0], 
                     user_err:    @room.errors.messages[:user_ids][0],
                     tag_err:     @room.errors.messages[:game_tag_ids][0],
                     content_err: @room.errors.messages[:content][0]
                    }
    end
  end

  def destroy
    room = Room.find(params[:id])
    room.destroy
    redirect_to root_path
  end

  def search
    @questions =       Room.search(current_user, params[:keyword])
    other_questions =  Room.search_other_questions
    @other_questions = Kaminari.paginate_array(other_questions).page(params[:page]).per(10)
  end

  private

  def room_params
    params.require(:room_message).permit(:question_title, :content).merge(user_ids: params[:room][:user_ids], game_tag_ids: params[:room][:game_tag_ids], user_id: current_user.id)
  end

  def check_if_user_signed_in
    redirect_to new_user_session_path unless user_signed_in?
  end
end

app/views/rooms/_error_messages.html.erb
<% if room.errors.any? %>
 <div class="error-alert">
   <ul>
     <% room.errors.full_messages.each do |message| %>
       <li class="error-message">
         <%= message %>
       </li>
     <% end %>
   </ul>
 </div>
<% end %>

app/views/rooms/_navigation_menu.html.erb
<div class="header-line">
  <header>

    <div class="header-left">
      <%= link_to root_path, class: "top-page" do %>
        <div class="app-name">Forte</div>
      <% end %>
      <% if user_signed_in? %>
        <div class="search-form">
          <%= form_with(url: search_rooms_path, local: true, method: :get, class: "search-form") do |form| %>
            <span class="fa-stack">
              <%= form.text_field :keyword, placeholder:"キーワードを入力", class: "search-input fa-lg fa-stack-2x" ,style:"width: 25vw; padding: 5px 5px 5px 32px; font-size: 1em; text-align: left;" %>
              <i class="fas fa-search fa-lg fa-stack-1x" style="font-size: 1em;"></i>
            </span>
            <%= form.submit "検索", type: "hidden", class: "search-btn" %>
          <% end %>
        </div>
      
        <% unless current_page?(notifications_path) %>
          <%= link_to(notifications_path) do %>
            <span class="fa-stack bell-position">
              <i class="far fa-bell fa-lg fa-stack-2x" style="font-size: 1.5em;" ></i>
              <% if unchecked_notifications.any? %>
              <% else %>
                <i class="fas fa-circle n-circle fa-stack-1x" style="font-size: 0.8em;" ></i>
              <% end %>
            </span>
          <% end %>
        <% end %>
      <% end %>
    </div>

    <div class="header-right">
      <% if user_signed_in? %>
        <div class="more-test">
        <span class="more-test-nickname"><%= current_user.nickname %></span>
      <div class="more">
        <div class="hover-icons">
          <% profile = current_user.profile %>
          <% if profile %>
            <% if profile.image? %>
                <%= image_tag(profile.image.thumb50.url)%>
            <% end %>
          <% else %>
            <%= image_tag "question_user_icon.png", class:"question-user-icon" %>
          <% end %>
          <%= image_tag "arrow_top.png"%>
        </div>
        <ul class="more_list">
            <li>
              <%= link_to 'マイページ', user_path(current_user), class: "my-page" %>
            </li>
            <li>
              <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "log-out" %>
            </li>
          </ul>
        </div>
        </div>
      <% elsif current_page?(root_path) %>
      <% else %>
      <div class="header__hover-action">
        <%= link_to '簡単ログイン', testsessions_path, class:"header-action", method: :post %>
      </div>
      <div class="header__hover-action">
        <%= link_to 'ログイン', new_user_session_path, class:"header-action" %>
      </div>
      <div class="header__hover-action">
        <%= link_to '新規登録', new_user_registration_path, class:"header-action" %>
      </div>
      <% end %>
    </div>
  </header>
</div>

app/views/rooms/_one_game_tag.html.erb
<div class="index">
  <div class="index-tag">
    <% tag = question.game_tags[0] %>
    <% if tag %>
      <%= link_to tag_search_game_tag_path(tag.id), class: 'game_tag__registration' do %>
        <%= tag.game_title %>
      <% end %>
    <% end %>
  </div>
  <div class="index-decoration"></div>
</div>

app/views/rooms/_one_question.html.erb
<% messages = question.messages %>
<% if messages[0] %>
  <% messages.size.times do |i| %>
    <div class="main-content">
      <div class="icons-space">
        <%= link_to user_path(messages[i].user) do %>
          <% profile = messages[i].user.profile %>
          <% if profile %>
            <% if profile.image? %>
              <%= image_tag(profile.image.thumb50.url, class: "question-user-icon")%>
            <% end %>
          <% else %>
            <% if messages.size == 1 %>
              <%= image_tag "question_user_icon.png", class:"question-user-icon" %>
            <% else %>
              <%= image_tag "answer_user_icon.png", class:"answer-user-icon" %>
            <% end %>
          <% end %>
        <% end %>
      </div>
      <div class="question-texts">
        <div class="question-nickname">
          <%= messages[i].user.nickname %>
        </div>
        <div class="question-sentence">
          <% if i == 0 %>
            <div class="question-Q">
              <i class="fab fa-quora"></i>.
            </div>
          <% else %>
            <div class="question-A">
              <%= "A." %>
            </div>
          <% end %>
          <div class="question-content">
            <%= safe_join("#{messages[i].content}".split("\n"),tag(:br))%>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/rooms/_question.html.erb
  
  <div class='question-form'>
    <div class="lets-question"><i class="fab fa-quora"></i> 質問フォーム</div>
    <%= form_with(url: rooms_path, model: @room, local: true, method: :post, id: 'form') do |f| %>
    <div id="error-lists">
      <div id="error">
      </div>
    </div>
    <%= render 'error_messages', room: @room %> 
    <div class='question-form__space'>
      <div class='question-form__field'>
        <label for="user", class='question__label'><i class="fas fa-user"></i> 回答して欲しいユーザー</label>
        <div class='question__field-right'>
          <select name="room[user_ids][]", id="user", class="answer__choose">
            <option value=""></option>
            <% User.all.where(id: current_user.followings).order("nickname").each do |user| %>
              <option value=<%=user.id%>><%= user.nickname %><%= "(フォロー)" %></option>
            <% end %>
            <% User.all.where(id: current_user.followers).where.not(id: current_user.followings).order("nickname").each do |user| %>
              <option value=<%=user.id%>><%= user.nickname %><%= "(フォロワー)" %></option>
            <% end %>
            <% User.all.where.not(id: current_user.followers).where.not(id: current_user.followings).where.not(id: current_user.id).order("nickname").each do |user| %>
              <option value=<%=user.id%>><%= user.nickname %></option>
            <% end %>
          </select>
          <input name="room[user_ids][]" type="hidden" value=<%=current_user.id%>>
        </div>
      </div>
      <div class='question-form__field'>
        <label for="game-tag", class='question__label'><i class="fas fa-gamepad"></i> ゲームタイトル</label>
        <div class='question__field-right'>
          <select name="room[game_tag_ids][]", id="game-tag", class="question-game-tag__choose">
            <option value=""></option>
            <% GameTag.all.order("game_title").each do |tag| %>
              <option value=<%=tag.id%>><%= tag.game_title %></option>
            <% end %>
          </select>
        </div>
      </div>
      </div>
      <div class='question-form__field'>
        <label for="question_title", class='question__label'><i class="fab fa-quora"></i>. 質問タイトル</label>
        <div class='question__field-right'>
          <%= f.text_field :question_title, class: 'question__room-name', id: "question_title"%>
        </div>
      </div>
      <div class='question-form__field'>
        <label for="content", class='question__label'><i class="far fa-comment-dots"></i> 質問本文</label>
        <div class='question__field-right'>
          <%= f.text_area :content, class: 'question__room_content', id: "content"%>
        </div>
      </div>
      <div class='question-form__field'>
        <div class='question__field-right'>
          <%= f.submit value="質問", class: 'question-btn', id: "submit" %>
        </div>
      </div>
    <% end %>
  </div>

app/views/rooms/_questions.html.erb
<div class="content">
  <%= render partial: "rooms/one_game_tag", locals: { question: question } %>
  <div class="room-name">
    <%= render partial: "rooms/title_line", locals: { question: question } %>
    <div class="panel"> <%# ↓モーダルに関する記述の始まり%>
      <% if question.messages.size == 1 && question.messages[0].user != current_user %>
          <%= render partial: "rooms/one_question", locals: { question: question } %>
      <% else %>
        <div class="c-btn js-open-modal"> <%# ↓モーダル画面を表示する判定の始まり%>
          <%= render partial: "rooms/one_question", locals: { question: question } %>
        </div> <%# ↑モーダル画面を表示する判定の終わり%>
      <% end %>
      <% if question.messages.size == 1 && question.messages[0].user != current_user %> 
        <div class="main-content">
          <div class="icons-space">
            <%= link_to user_path(question.entries[0].user) do %>
              <% profile_0 = question.entries[0].user.profile %>
              <% if profile_0 %>
                <% if profile_0.image? %>
                  <%= image_tag(profile_0.image.thumb50.url, class: "question-user-icon")%>
                <% end %>
              <% else %>
                <%= image_tag "answer_user_icon.png", class:"answer-user-icon" %>
              <% end %>
            <% end %>
          </div>
          <% if current_page?("/users/#{params[:id]}/") %>
            <div class="question-texts">
              <div class="question-nickname">
                <%= question.entries[0].user.nickname %>
              </div>

              <div class="question-sentence">
                <div class="question-A">
                  <%= "A." %>
                </div>
                <div class="question-content">
                  <span class="no-answer-text"><%= "まだ回答はありません" %></span>
                </div>
              </div>
            </div>
          <% else %>
            <div>
              <div id="error-lists-answer">
                <div id="error-answer">
                </div>
              </div>
              <div id="list-answer">
              </div>
              <%= form_with(url: messages_path, model: @message, local: true, method: :post, id: 'form-answer') do |f| %>
                <%= f.text_area :content, class: 'answer__room_content', id: "content-answer" %>
                <input name="room_id" type="hidden" value=<%= question.id %>>
                <%= f.submit '回答' , class: 'answer-btn', id: "submit-answer" %>
              <% end %>
            </div>
          <% end %>
        </div>
      <% end %>

      <div class="modal-panel-back disable"> <%# ↓隠れているモーダル画面の始まり%>
        <div class="modal-panel">
          <%= render partial: "rooms/one_game_tag", locals: { question: question } %>
          <%= render partial: "rooms/title_line", locals: { question: question } %>
          <%= render partial: "rooms/one_question", locals: { question: question } %>
        </div>
      </div> <%# ↑隠れているモーダル画面の終わり%>
    </div> <%# ↑モーダルに関する記述の終わり%>

    <div class="question-option">
      <div class="like">
        <div id="like-btn-<%= question.id %>">
          <%= render partial: "likes/like", locals: { room: question } %>
        </div>
      </div>
      <% question.messages.size.times do |i| %>
        <% if question.messages[i].user == current_user %>
          <%= link_to room_path(question), method: :delete , class: "delete-btn", data: { confirm: "本当に削除しますか？"}  do %>
            <i class="fas fa-trash"></i>
          <% end %>
          <% break %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/rooms/_questions_related_to_current_user.html.erb
<div class="content">
  <%= render partial: "one_game_tag", locals: { question: question } %>
  <div class="room-name">
    <div class="question-title">
      <%= question.question_title %>
    </div>
    <div class="panel"> <%# ↓モーダルに関する記述の始まり%>
      <% if question.messages.size == 1 && question.messages[0].user != current_user %>
          <%= render partial: "one_question", locals: { question: question } %>
      <% else %>
        <div class="c-btn js-open-modal"> <%# ↓モーダル画面を表示する判定の始まり%>
          <%= render partial: "one_question", locals: { question: question } %>
        </div> <%# ↑モーダル画面を表示する判定の終わり%>
      <% end %>
      <% if question.messages.size == 1 && question.messages[0].user != current_user %> 
        <div class="question-lists">
          <div class="icons-space">
            <%= link_to user_path(current_user) do %>
              <% unless current_user.profile == nil %>
                <% if current_user.profile.image? %>
                  <%= image_tag(current_user.profile.image.thumb50.url, class: "question-user-icon")%>
                <% end %>
              <% else %>
                <%= image_tag "answer_user_icon.png", class:"answer-user-icon" %>
              <% end %>
            <% end %>
          </div>
          <div>
            <div id="error-lists-answer">
              <div id="error-answer">
              </div>
            </div>
            <div id="list-answer">
            </div>
            <%= form_with(url: messages_path, model: @message, local: true, method: :post, id: 'form-answer') do |f| %>
              <%= f.text_area :content, class: 'answer__room_content', id: "content-answer" %>
              <input name="room_id" type="hidden" value=<%= question.id %>>
              <%= f.submit '回答' , class: 'answer-btn', id: "submit-answer" %>
            <% end %>
          </div>
        </div>
      <% end %>

      <div class="modal-panel-back disable"> <%# ↓隠れているモーダル画面の始まり%>
        <div class="modal-panel">
          <%= render partial: "one_game_tag", locals: { question: question } %>
          <div class="question-title">
            <%= question.question_title %>
          </div>
          <%= render partial: "one_question", locals: { question: question } %>
        </div>
      </div> <%# ↑隠れているモーダル画面の終わり%>
    </div> <%# ↑モーダルに関する記述の終わり%>

    <div class="question-option__space">
      <div class="like">
        <div id="like-btn-<%= question.id %>">
          <%= render partial: "likes/like", locals: { room: question } %>
        </div>
      </div>
      <%= link_to room_path(question), method: :delete , class: "question-delete-btn" do %>
        <i class="fas fa-trash"></i>
      <% end %>
    </div>
  </div>
</div>

app/views/rooms/_title_line.html.erb
<div class="title-line">
  <div class="question-title">
    <%= question.question_title %>
  </div>
  <div class="question-birth">
    <%= l question.created_at %>
  </div>
</div>

app/views/rooms/_top_page.html.erb
<div class="top-page__space">
  <div class="top-page-image__space">
    <%= image_tag "top-page-image.jpg", class: "top-page-image" %>
  </div>
  <div class="top-title__space" >
    Forte
  </div>
  <div class="top-content description__space" >
    <span class="more-forte">「もっと強くなりたい」</span> <br>
    強さを求めるゲーマーへ向けた、一問一答サービスです<br>
  </div>
  <div class="easy-login__space" >
    <div class="header__hover-action easy-login__btn">
      <%= link_to '簡単ログイン', testsessions_path, class:"header-action", method: :post %>
    </div>
  </div>
  <div class="user-action__space" >
    <div class="header__hover-action normal-login__btn">
      <%= link_to 'ログイン', new_user_session_path, class:"header-action" %>
    </div>
    <div class="header__hover-action normal-login__btn">
      <%= link_to '新規登録', new_user_registration_path, class:"header-action" %>
    </div>
  </div>

  <div class="app-descriprion">
  What is Forte?
  </div>
  <div class="all-descriptions__space">
    <div class="top-question__space">
      <div class="question-texts__space">
        <div class="question-text__space">トッププレイヤーに質問できます。</div>
          <div class="description__space">
            <span class="more-forte">「もっと強くなりたい!」</span><br>あなたの熱意を応援します!
          </div>
      </div>
      <div class="sample-image"><%= image_tag "top-sample-question.png", class: "sample-image" %></div>
    </div>

    <div class="top-question__space">
      <div class="question-texts__space">
        <div class="question-text__space">金銭的サポートも可能です。</div>
          <div class="description__space">
            <span class="more-forte">感謝を形に</span><br>プレイヤー同士で支援できます
          </div>
      </div>
      <div class="sample-image"><%= image_tag "top-sample-gift.png", class: "sample-image" %></div>
    </div>
  </div>


</div>

app/views/rooms/index.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
      <meta charset="UTF-8" />
      <title>Forte</title>
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.0.0/animate.min.css">
  </head>

  <body>
    <%= render partial: "navigation_menu" %>
    <main>
      <% if user_signed_in? %>
        <%= render partial: "question" %>
        <p><%= "#{current_user.nickname}さんに関連する質問" %></p>
        <div id="list">
        </div>
        <% @questions.each do |question| %>
          <%= render partial: "questions", locals: { question: question } %>
        <% end %>
        <p><%= "新着の質問" %></p>
        <% @other_questions.each do |question| %>
          <%= render partial: "questions", locals: { question: question } %>
        <% end %>
        <%= paginate @other_questions %>
      <% else %>
        <%= render partial: "top_page" %>
      <% end %>
    </main>
    <div>
      <% if user_signed_in? && Rails.env.test? %>
        <% num = 0 %>
        <% @users.where.not(id: current_user.id).each do |user| %>
          <p><%= link_to "#{user.nickname}の詳細ページ", user_path(user), class:"test-space" %></p>
          <% num += 1%>
          <% break if num == 4 %>
        <% end %>
      <% end %>
    </div>
  </body>
</html>

app/views/rooms/search.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <title>Forte</title>
  </head>

  <body>
    <%= render partial: "navigation_menu" %>
    <main>
      <% if user_signed_in? %>
        <p><%= "#{current_user.nickname}さんに関連する質問" %></p>
        <div id="list">
        </div>
        <% @questions.each do |question| %>
          <%= render partial: "questions", locals: { question: question } %>
        <% end %>
      <% end %>
      <p><%= "新着の質問" %></p>
      <% @other_questions.each do |question| %>
        <%= render partial: "questions", locals: { question: question } %>
      <% end %>
    </main>
  </body>
</html>